lesson: SpringBoot

enterprise:
  name: itcast
  age: 16
  tel: 135888
  subject:
    - java
    - 大数据
    - 前端
#设置启用的环境
spring:
  profiles:
  active: dev
---
server:
  port: 8080
spring:
  profiles: dev


---
server:
  port: 8081
spring:
    profiles: test

---
server:
  port: 8082
spring:
  profiles: pro


